"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { activeStudy,getStudyItem,setStudyItem,STUDY_CHANGED } from "../lib/workspace";
import type { SavedStudy } from "../lib/studyFormat";
import { DECISIONS,DECISION_DRAFT,blankDecision,createDecisionRecord,validateDecisionRecords,validateDecisionDraft,decisionSlots,decisionCandidateName,evidenceChanged,type DecisionDraft,type DecisionRecord } from "../lib/decisions";
import { studyReport,downloadStudy } from "../lib/studyReport";
const labels={preferred:"Preferred candidate for further work","insufficient-evidence":"Insufficient evidence to choose","no-suitable-candidate":"No suitable candidate in this shortlist"};
export function DecisionsView(){
  const [reviewedSnapshot,setReviewedSnapshot]=useState<SavedStudy>();
  const [study,setStudy]=useState<SavedStudy>(),[draft,setDraft]=useState<DecisionDraft>(blankDecision),[records,setRecords]=useState<DecisionRecord[]>([]),[error,setError]=useState(""),[ack,setAck]=useState(false),[notice,setNotice]=useState("");
  useEffect(()=>{try{const raw=JSON.parse(getStudyItem(DECISION_DRAFT)??"null");if(raw){validateDecisionDraft(raw);setDraft(raw);}}catch(e){setError(String(e));}const refresh=()=>{setStudy(activeStudy());setRecords(JSON.parse(getStudyItem(DECISIONS)??"[]"));};refresh();window.addEventListener(STUDY_CHANGED,refresh);return()=>window.removeEventListener(STUDY_CHANGED,refresh);},[]);
  const update=(patch:Partial<DecisionDraft>)=>{const next={...draft,...patch};setDraft(next);setAck(false);setNotice("");try{setStudyItem(DECISION_DRAFT,JSON.stringify(next));setError("");}catch(e){setError(String(e));}};
  const save=()=>{try{const current=activeStudy()!;if(!ack||!reviewedSnapshot||evidenceChanged({snapshot:reviewedSnapshot},current)){setAck(false);throw new Error("Study evidence changed after review. Review it again before recording.");}const history=JSON.parse(current.slices[DECISIONS]??"[]") as DecisionRecord[];const record=createDecisionRecord(current,draft,history);const next=[...history,record];validateDecisionRecords(next);setStudyItem(DECISIONS,JSON.stringify(next));setNotice("Decision recorded with a frozen evidence snapshot.");setAck(false);setError("");}catch(e){setError(e instanceof Error?e.message:String(e));}};
  if(!study)return null;
  const slots=decisionSlots(study),alternatives=slots.filter((s)=>draft.outcome!=="preferred"||s.conditionId!==draft.selectedConditionId);
  return <><div className="pane-header"><h1>Decision record</h1><span className="count">{records.length} recorded revisions</span><Link className="btn ghost" href="/comparisons">Review comparison</Link><Link className="btn ghost" href="/verification">Verification plan</Link></div><div className="records-content">
  <p>Record the engineering judgment and evidence used to choose a candidate or defer the choice. Each saved revision preserves the duty, shortlist, material records, rule settings, saved results and verification history.</p>
  <p className="calc-src">Reviewer names are self-reported, not authenticated signatures. A recorded preference is for further investigation; it does not approve a material. Saved calculations retain their own input snapshots and are not recomputed when recording.</p>
  <h2>{records.length?"Record a new revision":"Draft decision"}</h2><div className="record-fields"><label>Outcome<select value={draft.outcome} onChange={(e)=>update({outcome:e.target.value as DecisionDraft["outcome"]})}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{draft.outcome==="preferred"&&<label>Preferred candidate<select value={draft.selectedConditionId} onChange={(e)=>update({selectedConditionId:e.target.value})}><option value="">Choose a condition</option>{slots.filter((s)=>!s.excluded).map((s)=><option key={s.conditionId} value={s.conditionId}>{decisionCandidateName(study,s)}</option>)}</select></label>}<label>Reviewer / decision author<input maxLength={10000} value={draft.reviewer} onChange={(e)=>update({reviewer:e.target.value})}/></label></div>
  <label>Engineering rationale<textarea maxLength={10000} value={draft.rationale} placeholder="Explain the trade-offs, evidence and assumptions behind this outcome." onChange={(e)=>update({rationale:e.target.value})}/></label>
  <label>Unresolved questions and required next steps<textarea maxLength={10000} value={draft.unresolved} placeholder="State remaining checks, or explicitly record that none were identified within the study scope." onChange={(e)=>update({unresolved:e.target.value})}/></label>
  {!!alternatives.length&&<h3>Disposition of alternatives</h3>}{alternatives.map((slot)=><label key={slot.conditionId}>{decisionCandidateName(study,slot)}<textarea maxLength={10000} aria-label={`Disposition for ${decisionCandidateName(study,slot)}`} value={draft.alternatives[slot.conditionId]??""} placeholder="Why rejected, retained as a backup, or not yet distinguishable?" onChange={(e)=>update({alternatives:{...draft.alternatives,[slot.conditionId]:e.target.value}})}/></label>)}
  <label className="decision-ack"><input type="checkbox" checked={ack} onChange={(e)=>{setAck(e.target.checked);setReviewedSnapshot(e.target.checked?JSON.parse(JSON.stringify(activeStudy())):undefined);}}/>I reviewed the supporting comparison, saved result inputs and verification actions for this decision.</label><button className="btn" disabled={!ack} onClick={save}>Record decision snapshot</button>{error&&<p className="calc-warn" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <h2>Recorded history</h2>{!records.length&&<p>No decision recorded yet. Draft changes are saved with this study.</p>}{[...records].reverse().map((r,i)=><article className="verification-task" key={r.id}><h3>{labels[r.outcome]}{i?" · superseded":" · latest record"}</h3><p>{r.reviewer} · {new Date(r.recordedAt).toLocaleString()}</p><p>{r.selected?decisionCandidateName(r.snapshot,r.selected):"No candidate selected"}</p>{evidenceChanged(r,study)&&<p className="calc-warn">Study evidence has changed since this decision. Review the changes and record a new revision.</p>}<p>{r.rationale}</p><p><strong>Unresolved:</strong> {r.unresolved}</p><details><summary>Alternatives and frozen evidence</summary>{r.alternatives.map((a)=><p key={a.candidate.conditionId}><strong>{decisionCandidateName(r.snapshot,a.candidate)}:</strong> {a.reason}</p>)}<p>{Object.keys(r.snapshot.slices).length} frozen study sections · dataset {r.snapshot.references.datasetVersion}</p><button className="btn ghost" onClick={()=>downloadStudy(studyReport({...r.snapshot,slices:{...r.snapshot.slices,[DECISIONS]:JSON.stringify([r])}}),`alloyra-decision-${r.id}.html`,"text/html")}>Download decision report</button></details></article>)}<p><Link href="/studies">Export complete study and decision history →</Link></p>
  </div></>;
}
