"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { alloys } from "@alloyra/data";
import { MATERIAL_RECORDS, MATERIAL_CSV_TEMPLATE, TEST_PROPERTIES, ELEMENTS, materialRecordsFromCsv, validateMaterialRecords, type MaterialRecord, type TestProperty } from "../lib/materialRecords";
import { getStudyItem, setStudyItem, readWorkspace, STUDY_CHANGED } from "../lib/workspace";
import { loadStored, saveComparison } from "../lib/comparison";
import { downloadStudy } from "../lib/studyReport";
type Entry = { kind: "chemistry"|"test"; name: string; value: string; temp: string };
const quote=(v:string)=>`"${v.replace(/"/g,'""')}"`;
export function MaterialRecordsView() {
  const router=useRouter();
  const [records,setRecords]=useState<MaterialRecord[]>([]), [preview,setPreview]=useState<MaterialRecord[]>([]), [error,setError]=useState(""), [message,setMessage]=useState("");
  const [uns,setUns]=useState("S31603"), [conditionId,setConditionId]=useState(alloys.find((a)=>a.uns==="S31603")!.conditions[0]!.id);
  const [heatId,setHeatId]=useState(""),[form,setForm]=useState(""),[thickness,setThickness]=useState(""),[source,setSource]=useState("");
  const [entries,setEntries]=useState<Entry[]>([{kind:"chemistry",name:"Cr",value:"",temp:""}]);
  const refresh=()=>{try{setRecords(JSON.parse(getStudyItem(MATERIAL_RECORDS)??"[]"));}catch(e){setError(String(e));}};
  useEffect(()=>{refresh();window.addEventListener(STUDY_CHANGED,refresh);return()=>window.removeEventListener(STUDY_CHANGED,refresh);},[]);
  const show=(raw:string)=>{try{const next=materialRecordsFromCsv(raw);validateMaterialRecords(next,alloys);setPreview(next);setError("");setMessage("");}catch(e){setPreview([]);setError(e instanceof Error?e.message:String(e));}};
  const change=(i:number,patch:Partial<Entry>)=>{setEntries((rows)=>rows.map((r,j)=>j===i?{...r,...patch}:r));setPreview([]);};
  const save=()=>{try{const current=JSON.parse(getStudyItem(MATERIAL_RECORDS)??"[]") as MaterialRecord[];const next=[...current,...preview];validateMaterialRecords(next,alloys);setStudyItem(MATERIAL_RECORDS,JSON.stringify(next));setMessage(`Saved ${preview.length} material record(s). Select a record below to use its measured values in comparison.`);setPreview([]);refresh();}catch(e){setError(String(e));}};
  const useRecord=(record:MaterialRecord)=>{const c=loadStored();const existing=c.slots.find((s)=>s.conditionId===record.conditionId);if(!existing&&c.slots.length>=6){setError("The comparison has six conditions. Remove one before adding this record.");return;}const slots=existing?c.slots.map((s)=>s===existing?{...s,materialRecordId:record.id}:s):[...c.slots,{uns:record.uns,conditionId:record.conditionId,materialRecordId:record.id,pinned:false,excluded:false}];if(!saveComparison({...c,slots,overrideLog:[...c.overrideLog,`${new Date().toISOString()}: selected measured heat ${record.heatId} for ${record.conditionId}`]})){setError("Could not save the comparison selection.");return;}router.push("/comparisons");};
  return <><div className="pane-header"><h1>Material records</h1><span className="count">{records.length} saved</span><Link className="btn ghost" href="/verification">Verification plan →</Link></div><div className="records-content">
  <p>Enter measurements from a supplier certificate or an internal test report. They remain separate from specification midpoints. Missing chemistry and tests stay unknown. Source text identifies the evidence; files are not independently authenticated.</p>
  <details open><summary>Add a measured record</summary><div className="record-fields">
    <label>Reference grade<select value={uns} onChange={(e)=>{setUns(e.target.value);setConditionId(alloys.find((a)=>a.uns===e.target.value)!.conditions[0]!.id);setPreview([]);}}>{alloys.map((a)=><option key={a.uns} value={a.uns}>{a.names[0]} · {a.uns}</option>)}</select></label>
    <label>Reported condition<select value={conditionId} onChange={(e)=>{setConditionId(e.target.value);setPreview([]);}}>{alloys.find((a)=>a.uns===uns)!.conditions.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label>Heat / lot identifier<input value={heatId} onChange={(e)=>{setHeatId(e.target.value);setPreview([]);}} /></label>
    <label>Product form<input placeholder="e.g. plate" value={form} onChange={(e)=>{setForm(e.target.value);setPreview([]);}} /></label>
    <label>Thickness (mm), blank if unknown<input inputMode="decimal" value={thickness} onChange={(e)=>{setThickness(e.target.value);setPreview([]);}} /></label>
    <label>Source / certificate reference<input placeholder="Certificate number, issuer, date or test report" value={source} onChange={(e)=>{setSource(e.target.value);setPreview([]);}} /></label>
  </div><p className="calc-src">Enter reported numeric values only. Do not turn “less than” limits into measured zeros. Record each chemistry element in wt%; no balance is inferred. For tests, enter the actual test temperature, not the service temperature.</p>
  {entries.map((r,i)=><div className="measurement-row" key={i}><label>{r.kind==="chemistry"?"Element":"Test property"}<select aria-label={`Measurement ${i+1} name`} value={r.name} onChange={(e)=>change(i,{name:e.target.value})}>{(r.kind==="chemistry"?ELEMENTS:Object.keys(TEST_PROPERTIES)).map((k)=><option key={k} value={k}>{k.replace(/_/g," ")}</option>)}</select></label><label>Value ({r.kind==="chemistry"?"wt%":TEST_PROPERTIES[r.name as TestProperty]})<input aria-label={`Measurement ${i+1} value`} inputMode="decimal" value={r.value} onChange={(e)=>change(i,{value:e.target.value})} /></label>{r.kind==="test"&&<label>Test temperature (°C)<input aria-label={`Measurement ${i+1} test temperature`} inputMode="decimal" value={r.temp} onChange={(e)=>change(i,{temp:e.target.value})} /></label>}<button className="btn ghost" onClick={()=>{setEntries((rows)=>rows.filter((_,j)=>i!==j));setPreview([]);}}>Remove measurement {i+1}</button></div>)}
  <div className="study-actions"><button className="btn ghost" onClick={()=>{setEntries((r)=>[...r,{kind:"chemistry",name:"Ni",value:"",temp:""}]);setPreview([]);}}>Add chemistry value</button><button className="btn ghost" onClick={()=>{setEntries((r)=>[...r,{kind:"test",name:"yield_strength",value:"",temp:""}]);setPreview([]);}}>Add test result</button><button className="btn" onClick={()=>show(MATERIAL_CSV_TEMPLATE+entries.map((r)=>[heatId,uns,conditionId,form,thickness,source,r.kind,r.name,r.value,r.kind==="chemistry"?"wt%":TEST_PROPERTIES[r.name as TestProperty],r.temp].map(quote).join(",")).join("\n"))}>Review record</button></div></details>
  <details><summary>Import measured records from CSV</summary><p>One measurement per row. Repeat heat, grade, condition, form, thickness and source for each measurement in a record. Supported kinds: chemistry and test. Chemistry uses element symbols; tests use yield_strength, tensile_strength, elongation or density. Units must match the template instructions above.</p><p>Current condition IDs: <select aria-label="CSV condition ID reference">{alloys.flatMap((a)=>a.conditions.map((c)=><option key={c.id}>{a.uns} · {c.name} → {c.id}</option>))}</select></p><div className="study-actions"><button className="btn ghost" onClick={()=>downloadStudy(MATERIAL_CSV_TEMPLATE,"alloyra-measurements-template.csv","text/csv")}>Download CSV template</button><label>Choose measurement CSV<input type="file" accept=".csv,text/csv" onChange={async(e)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(file.size>2_000_000){setError("CSV exceeds 2 MB.");return;}const origin=readWorkspace().activeId;try{const raw=await file.text();if(readWorkspace().activeId===origin)show(raw);}catch(e){setError(String(e));}}} /></label></div></details>
  {error&&<p role="alert" className="calc-warn">{error}</p>}{message&&<p role="status">{message}</p>}
  {!!preview.length&&<section className="record-preview"><h2>Review before saving ({preview.length})</h2><p>These are user-supplied measurements, not specification guarantees or design allowables. Check heat, condition, units and temperatures against the original evidence.</p>{preview.map((r)=><RecordSummary key={r.id} record={r}/>)}<button className="btn" onClick={save}>Save reviewed records</button></section>}
  <h2>Saved evidence</h2><p className="calc-src">Records are immutable. Add a corrected record and select it to change comparison inputs. One measured record can be selected per reference condition at a time.</p>{records.map((r)=><article className="material-record" key={r.id}><RecordSummary record={r}/><button className="btn" onClick={()=>useRecord(r)}>Use heat {r.heatId} in comparison</button></article>)}
  </div></>;
}
function RecordSummary({record:r}:{record:MaterialRecord}) {return <><h3>{r.heatId} · {r.uns} · {alloys.find((a)=>a.uns===r.uns)?.conditions.find((c)=>c.id===r.conditionId)?.name ?? r.conditionId}</h3><p>{r.form} · thickness {r.thicknessMm===null?"unknown":`${r.thicknessMm} mm`}<br/>Source: {r.source}</p><p>Chemistry (wt%): {Object.entries(r.chemistry).map(([el,n])=>`${el} ${n}`).join(" · ")||"not reported"}. Reported total: {Object.values(r.chemistry).reduce((a,b)=>a+(b??0),0).toFixed(3)}%.</p>{r.tests.map((t,i)=><p key={i}>{t.property.replace(/_/g," ")}: {t.value} {t.unit} at {t.testTempC} °C · {t.source}</p>)}</>;}
