"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { alloys } from "@alloyra/data";
import { loadStored } from "../lib/comparison";
import { loadProfiles, dutyFromProfile } from "../lib/profiles";
import { activeRules, loadOverlay } from "../lib/rules";
import { getStudyItem, setStudyItem, STUDY_CHANGED } from "../lib/workspace";
import { MATERIAL_RECORDS } from "../lib/materialRecords";
import { VERIFICATION, verificationTasks, taskUpdate, validateVerification, type VerificationTask, type VerificationUpdate } from "../lib/verification";
export function VerificationView() {
  const [candidateFilter,setCandidateFilter]=useState("");
  const [loaded,setLoaded]=useState(false);
  const [tasks,setTasks]=useState<VerificationTask[]>([]),[history,setHistory]=useState<VerificationUpdate[]>([]),[error,setError]=useState("");
  const refresh=()=>{try{const c=loadStored(),profile=loadProfiles().find((p)=>p.id===c.profileId);setTasks(verificationTasks({alloys,slots:c.slots,records:JSON.parse(getStudyItem(MATERIAL_RECORDS)??"[]"),duty:profile?dutyFromProfile(profile):null,rules:activeRules(loadOverlay(),{includeDrafts:c.includeDrafts}),weights:c.weights}));setHistory(JSON.parse(getStudyItem(VERIFICATION)??"[]"));setLoaded(true);}catch(e){setError(String(e));}};
  useEffect(()=>{refresh();window.addEventListener(STUDY_CHANGED,refresh);return()=>window.removeEventListener(STUDY_CHANGED,refresh);},[]);
  const save=(update:VerificationUpdate)=>{try{const next=[...JSON.parse(getStudyItem(VERIFICATION)??"[]"),update];validateVerification(next);setStudyItem(VERIFICATION,JSON.stringify(next));setError("");refresh();return true;}catch(e){setError(String(e));return false;}};
  const snapshot=JSON.stringify({modelVersion:"alloyra-verification-v1",inputs:{taskBases:tasks.map((t)=>({id:t.id,basis:t.basis}))},results:tasks.map((task)=>{const {update,stale}=taskUpdate(task,history);return {...task,owner:update?.owner??"",status:stale?"needs-review":update?.status??"open",resolution:stale?"":update?.resolution??""};})});
  useEffect(()=>{if(loaded){try{setStudyItem("alloyra.verificationResults.v1",snapshot);}catch(e){setError(String(e));}}},[loaded,snapshot]);
  const resolved=tasks.filter((t)=>{const {update,stale}=taskUpdate(t,history);return !stale&&update?.status==="resolved";}).length;
  return <><div className="pane-header"><h1>Verification plan</h1><span className="count">{tasks.length-resolved} open · {resolved} resolved</span><Link className="btn ghost" href="/records">Material records</Link><Link className="btn ghost" href="/profiles">Duty profiles</Link></div><div className="records-content"><p>Actions come from the current comparison, selected material evidence, duty and active rules. Resolution notes document your review; they do not fill missing values, change scores, validate rules or approve a material.</p><p className="calc-src">When the underlying inputs change, previous resolutions require review again. Tasks that no longer apply disappear from the current plan; their saved history remains below and in the study export.</p>{error&&<p className="calc-warn" role="alert">{error}</p>}{!tasks.length&&<p>No automated gaps detected. This does not establish material suitability; record any additional engineering checks in your assessment.</p>}<label className="verification-filter">Show candidate<select value={candidateFilter} onChange={(e)=>setCandidateFilter(e.target.value)}><option value="">All candidates</option>{[...new Set(tasks.map((t)=>t.candidate))].map((name)=><option key={name}>{name}</option>)}</select></label>{tasks.filter((t)=>!candidateFilter||t.candidate===candidateFilter).map((task)=>{const {update,stale}=taskUpdate(task,history);return <TaskCard key={`${task.id}:${task.basis}:${update?.updatedAt??""}`} task={task} update={update} stale={stale} save={save}/>;})}<details><summary>Saved verification history ({history.length})</summary>{[...history].reverse().map((u,i)=><article key={i}><h3>{u.candidate} · {u.title}</h3><p>{u.status} · {u.owner||"Unassigned"} · {u.updatedAt}</p><p>{u.resolution||"No resolution note"}</p></article>)}</details><p><Link href="/studies">Export this plan with the study →</Link></p></div></>;
}
function TaskCard({task,update,stale,save}:{task:VerificationTask;update:VerificationUpdate|undefined;stale:boolean;save:(u:VerificationUpdate)=>boolean}) {
  const [owner,setOwner]=useState(update?.owner??""),[status,setStatus]=useState<VerificationUpdate["status"]>(stale?"open":update?.status??"open"),[resolution,setResolution]=useState(stale?"":update?.resolution??""),[saved,setSaved]=useState(false);
  return <article className="verification-task"><p className="calc-src">{task.candidate}</p><h2>{task.title}</h2><p>{task.action}</p>{stale&&<p className="calc-warn">Inputs changed. Review this action again. Previous note: {update?.resolution||"none"}</p>}<div className="record-fields"><label>Owner<input value={owner} onChange={(e)=>{setOwner(e.target.value);setSaved(false);}} /></label><label>Status<select value={status} onChange={(e)=>{setStatus(e.target.value as VerificationUpdate["status"]);setSaved(false);}}><option value="open">Open</option><option value="in-progress">In progress</option><option value="resolved">Resolved by reviewer</option></select></label></div><label>Evidence / resolution note<textarea value={resolution} placeholder="What was checked, source, findings, and any remaining limitations" onChange={(e)=>{setResolution(e.target.value);setSaved(false);}} /></label><button className="btn" disabled={status==="resolved"&&!resolution.trim()} onClick={()=>setSaved(save({...task,owner,status,resolution,updatedAt:new Date().toISOString()}))}>Save action update</button>{saved&&<span role="status"> Saved</span>}</article>;
}
